require('./assets.test');
require('./assets-health.test');
require('./captions.test');
require('./codex-args.test');
require('./codex-parser.test');
require('./codex-stderr-filter.test');
require('./agent-health.test');
require('./agent-logs.test');
require('./config.test');
require('./render-validation.test');
require('./render-settings.test');
require('./paths.test');
require('./repair.test');
require('./showcase.test');
require('./templates.test');
require('./template-packs.test');
require('./template-packs-url.test');
require('./timeline.test');
require('./variations.test');
require('./render-queue.test');
require('./sessions.test');

console.log('all tests passed');
